package com.example.dbapi.dao;

import java.sql.ResultSet;
import java.sql.SQLException;

import com.example.dbapi.models.PersonalInfo;

import com.example.dbapi.models.PersonalSecret;
import org.springframework.jdbc.core.RowMapper;

public class PersonalSecretMapper implements RowMapper<PersonalSecret> {

    @Override
    public PersonalSecret mapRow(ResultSet rs, int rowNum) throws SQLException {
        PersonalSecret personalSecret = new PersonalSecret();
        personalSecret.setInputCode(rs.getString("input_code"));
//        personalSecret.setMotoCode(rs.getString("moto_code"));
        personalSecret.setClassCode(rs.getString("class_code"));
        personalSecret.setTourokumei(rs.getString("tourokumei"));
        personalSecret.setTourokumeiYomi(rs.getString("tourokumei_yomi"));
        personalSecret.setHonmyou(rs.getString("honmyou"));
        personalSecret.setHonmyouYomi(rs.getString("honmyou_yomi"));
        personalSecret.setHitsumei(rs.getString("hitsumei"));
        personalSecret.setHitsumeiYomi(rs.getString("hitsumei_yomi"));
        personalSecret.setSeijiSetsumei(rs.getString("seiji_setsumei"));
        personalSecret.setSeibetsu(rs.getString("seibetsu"));
        personalSecret.setSeinengappi(rs.getString("seinengappi"));
        personalSecret.setWarekiSeinen(rs.getString("wareki_seinen"));
        personalSecret.setShusseiTodouhuken(rs.getString("shussei_todouhuken"));
        personalSecret.setShusseiShichou(rs.getString("shussei_shichou"));
        personalSecret.setShusshinTodouhuken(rs.getString("shusshin_todouhuken"));
        personalSecret.setShusshinShichou(rs.getString("shusshin_shichou"));
        personalSecret.setShibouNichiji(rs.getString("shibou_nichiji"));
        personalSecret.setGakureki(rs.getString("gakureki"));
        personalSecret.setGenshoku(rs.getString("genshoku"));
        personalSecret.setSenkyoku(rs.getString("senkyoku"));
        personalSecret.setKaiha(rs.getString("kaiha"));
        personalSecret.setSeitou(rs.getString("seitou"));
        personalSecret.setTousenKaisuu(rs.getInt("tousen_kaisuu"));
        personalSecret.setShozoku(rs.getString("shozoku"));
        personalSecret.setMotoshoku(rs.getString("motoshoku"));
        personalSecret.setKeireki(rs.getString("keireki"));
        personalSecret.setSenmonBunya(rs.getString("senmon_bunya"));
        personalSecret.setGyouseki(rs.getString("gyouseki"));
        personalSecret.setGakui(rs.getString("gakui"));
        personalSecret.setJushou(rs.getString("jushou"));
        personalSecret.setJitakuYuubinbangou(rs.getString("jitaku_yuubinbangou"));
        personalSecret.setJitakuJuusho(rs.getString("jitaku_juusho"));
        personalSecret.setJitakuMeishou(rs.getString("jitaku_meishou"));
        personalSecret.setJitakuDenwa(rs.getString("jitaku_denwa"));
        personalSecret.setJitakuFax(rs.getString("jitaku_fax"));
        personalSecret.setRenrakusakiYuubinbangou(rs.getString("renrakusaki_yuubinbangou"));
        personalSecret.setRenrakusakiJuusho(rs.getString("renrakusaki_juusho"));
        personalSecret.setRenrakusakiMeishou(rs.getString("renrakusaki_meishou"));
        personalSecret.setRenrakusakiDenwa(rs.getString("renrakusaki_denwa"));
        personalSecret.setRenrakusakiDenwaShurui(rs.getString("renrakusaki_denwa_shurui"));
        personalSecret.setRenrakusakiDenwaNaisen(rs.getString("renrakusaki_denwa_naisen"));
        personalSecret.setRenrakusakiFax(rs.getString("renrakusaki_fax"));
        personalSecret.setRenrakusakiFaxShurui(rs.getString("renrakusaki_fax_shurui"));
//        personalSecret.setShoukenCode(rs.getString("shouken_code"));
        personalSecret.setKeitaidenwa(rs.getString("keitaidenwa"));
        personalSecret.setEmail(rs.getString("email"));
        personalSecret.setHomepage(rs.getString("homepage"));
        personalSecret.setSouhusakiYuubinbangou(rs.getString("souhusaki_yuubinbangou"));
        personalSecret.setSouhusakiJuusho(rs.getString("souhusaki_juusho"));
        personalSecret.setSouhusakiMeishou(rs.getString("souhusaki_meishou"));
        personalSecret.setSouhusakiDenwa(rs.getString("souhusaki_denwa"));
        personalSecret.setSouhusakiDenwaShurui(rs.getString("souhusaki_denwa_shurui"));
        personalSecret.setSouhusakiDenwaNaisen(rs.getString("souhusaki_denwa_naisen"));
        personalSecret.setSouhusakiFax(rs.getString("souhusaki_fax"));
        personalSecret.setSouhusakiFaxShurui(rs.getString("souhusaki_fax_shurui"));
        personalSecret.setShumi(rs.getString("shumi"));
        personalSecret.setKakusiKeisaiKiji(rs.getString("kakusi_keisai_kiji"));
        personalSecret.setBikou(rs.getString("bikou"));
//        personalSecret.setAsahiJinbutsuJiten(rs.getString("asahi_jinbutsu_jiten"));
//        personalSecret.setHenshuubuTyuu(rs.getString("henshuubu_tyuu"));
        personalSecret.setKoutekiShokumushaFlag(rs.getString("kouteki_shokumusha_flag"));
        personalSecret.setMinkanChomeijinFlag(rs.getString("minkan_chomeijin_flag"));
//        personalSecret.setResearchAtenaFlag(rs.getString("research_atena_flag"));
//        personalSecret.setResearchAtesakiFlag(rs.getString("research_atesaki_flag"));
//        personalSecret.setDantaiStatus(rs.getString("dantai_status"));
//        personalSecret.setInputDate(rs.getDate("input_date"));
//        personalSecret.setInputAuthor(rs.getString("input_author"));
//        personalSecret.setCreateMethod(rs.getString("create_method"));
        personalSecret.setUpdateDate(rs.getDate("update_date"));
        personalSecret.setUpdateHistory(rs.getString("update_history"));
//        personalSecret.setPublicationCondition(rs.getString("publication_condition"));
//        personalSecret.setChiezouKouho(rs.getString("chiezou_kouho"));
        personalSecret.setHonmyouPub(rs.getString("honmyou_pub"));
        personalSecret.setHitsumeiPub(rs.getString("hitsumei_pub"));
        personalSecret.setSeijiSetsumeiPub(rs.getString("seiji_setsumei_pub"));
        personalSecret.setSeibetsuPub(rs.getString("seibetsu_pub"));
        personalSecret.setSeinengappiPub(rs.getString("seinengappi_pub"));
        personalSecret.setShusseiTodouhukenPub(rs.getString("shussei_todouhuken_pub"));
        personalSecret.setShusseiShichouPub(rs.getString("shussei_shichou_pub"));
        personalSecret.setShusshinTodouhukenPub(rs.getString("shusshin_todouhuken_pub"));
        personalSecret.setShusshinShichouPub(rs.getString("shusshin_shichou_pub"));
        personalSecret.setGakurekiPub(rs.getString("gakureki_pub"));
        personalSecret.setGenshokuPub(rs.getString("genshoku_pub"));
        personalSecret.setShozokuPub(rs.getString("shozoku_pub"));
        personalSecret.setMotoshokuPub(rs.getString("motoshoku_pub"));
        personalSecret.setKeirekiPub(rs.getString("keireki_pub"));
        personalSecret.setSenmonBunyaPub(rs.getString("senmon_bunya_pub"));
        personalSecret.setGyousekiPub(rs.getString("gyouseki_pub"));
        personalSecret.setGakuiPub(rs.getString("gakui_pub"));
        personalSecret.setJushouPub(rs.getString("jushou_pub"));
        personalSecret.setJitakuJuushoPub(rs.getString("jitaku_juusho_pub"));
        personalSecret.setJitakuDenwaPub(rs.getString("jitaku_denwa_pub"));
        personalSecret.setJitakuFaxPub(rs.getString("jitaku_fax_pub"));
        personalSecret.setRenrakusakiJuushoPub(rs.getString("renrakusaki_juusho_pub"));
        personalSecret.setRenrakusakiDenwaPub(rs.getString("renrakusaki_denwa_pub"));
        personalSecret.setRenrakusakiFaxPub(rs.getString("renrakusaki_fax_pub"));
        personalSecret.setKeitaidenwaPub(rs.getString("keitaidenwa_pub"));
        personalSecret.setEmailPub(rs.getString("email_pub"));
        personalSecret.setHomepagePub(rs.getString("homepage_pub"));
        personalSecret.setSouhusakiJuushoPub(rs.getString("souhusaki_juusho_pub"));
        personalSecret.setSouhusakiDenwaPub(rs.getString("souhusaki_denwa_pub"));
        personalSecret.setSouhusakiFaxPub(rs.getString("souhusaki_fax_pub"));
        personalSecret.setShumiPub(rs.getString("shumi_pub"));
        personalSecret.setJinbutsuPub(rs.getString("jinbutsu_pub"));
        personalSecret.setFreewordData(rs.getString("freeword_data"));
        personalSecret.setIntaiFlag(rs.getString("intai_flag"));
		return personalSecret;
    }

}
