INSERT INTO public.work_personal_info
(input_code, class_code, tourokumei, tourokumei_yomi, honmyou, honmyou_yomi, hitsumei, hitsumei_yomi, seiji_setsumei, seibetsu, seinengappi, wareki_seinen, shussei_todouhuken, shussei_shichou, shusshin_todouhuken, shusshin_shichou, shibou_nichiji, gakureki, genshoku, senkyoku, kaiha, seitou, tousen_kaisuu, shozoku, motoshoku, keireki, senmon_bunya, gyouseki, gakui, jushou, jitaku_yuubinbangou, jitaku_juusho, jitaku_meishou, jitaku_denwa, jitaku_fax, renrakusaki_yuubinbangou, renrakusaki_juusho, renrakusaki_meishou, renrakusaki_denwa, renrakusaki_denwa_shurui, renrakusaki_denwa_naisen, renrakusaki_fax, renrakusaki_fax_shurui, keitaidenwa, email, homepage, souhusaki_yuubinbangou, souhusaki_juusho, souhusaki_meishou, souhusaki_denwa, souhusaki_denwa_shurui, souhusaki_denwa_naisen, souhusaki_fax, souhusaki_fax_shurui, shumi, kakusi_keisai_kiji, bikou, asahi_jinbutsu_jiten, henshuubu_tyuu, kouteki_shokumusha_flag, minkan_chomeijin_flag, research_atena_flag, research_atesaki_flag, input_author, create_method, new_create_status, new_create_author, maintenance_author, checker_status, checker_author, new_create_approver, maintenance_approver, checker_approver, update_history, message_history, publication_history, latest_research_year, maintenance_priority, maintenance_research_status, maintenance_modifier, honmyou_pub, hitsumei_pub, seiji_setsumei_pub, seibetsu_pub, seinengappi_pub, shussei_todouhuken_pub, shussei_shichou_pub, shusshin_todouhuken_pub, shusshin_shichou_pub, gakureki_pub, genshoku_pub, shozoku_pub, motoshoku_pub, keireki_pub, senmon_bunya_pub, gyouseki_pub, gakui_pub, jushou_pub, jitaku_juusho_pub, jitaku_denwa_pub, jitaku_fax_pub, renrakusaki_juusho_pub, renrakusaki_denwa_pub, renrakusaki_fax_pub, keitaidenwa_pub, email_pub, homepage_pub, souhusaki_juusho_pub, souhusaki_denwa_pub, souhusaki_fax_pub, shumi_pub, jinbutsu_pub, freeword_data, maintenance_verify_author, intai_flag )
VALUES('000001', '021', '朝日', 'あさひ', '朝日　太陽', 'あさひ　たいよう', '安倍　晋三', 'あべ　しんぞう', '別名は阿部信三という', '男性', '19750101', 'R02', '山口県', '大津郡油谷町', '大阪府', '大阪市', '20200101', '成蹊大学法学部政治学科　成蹊高等学校　成蹊中学校　成蹊小学校', '株式会社ナル', '海部郡', '自由民主党・無所属の会', '自由民主党', 3, '第一銀行', '株式会社SRA', '1999年　第一銀行入社／2012年04月 フィナンシャルグループ執行役員／2019年04月 同常務執行役員、第一銀行常務取締役／2020年10月 グループ取締役兼執行役常務／2020年11月 第一銀行代表取締役頭取／', '建築デザイン
グラフィックデザイン
フォトグラフ', '東京タワー内装デザイン(1958)
グラフィックデザインと写真個展(2018)', '色彩検定1級(2006)
1級鮪解体師(2009)', '朝日賞受賞(1929)
「日本の自然風景」フォトコンテスト(2018)', '1690072', '北新宿２−２−１９', '第一銀行', '0-3-5952-1311', '0-3-5952-1866', '1690074', '北新宿２−２−１７', '第一銀行', '0-3-5952-1313', 'M', '03-5952-1866', '0-3-5952-1866', 'M', '0-80-04947-6688', 'test@test.com', 'test.com.jp', '1690073', '北新宿２−２−１８', '第一銀行', '0-3-5952-1312', 'D', '03-3592-1312', '03-3592-1312', 'M', 'ゴルフ', '朝日賞受賞(1929)', 'テスト', '', '', '0', '0', '0', '0', '田中', '', '', '', '', '', '', '', '', '', '2019.03.15(2019.03.31協会会長退任) 2018.09.20(学歴追加)
2018.04.02(2018.04.01日本銀行参与) 2018.03.29(2018.04.01協会
会長) 2017.09.11(〆作業)', '', '', '', '', '', '', '0', '1', '2', '0', '1', '2', '0', '1', '2', '0', '1', '2', '0', '1', '2', '0', '1', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'アイウエオ　かきくけこ　テスト', '', '0');
